#test
version: '3'

services:
  identity: 
    build:
      context: ../
      dockerfile: './ecommerce-identity/Dockerfile'
    ports:
      - "8080:80"
  api: 
    build: 
      context: ../
      dockerfile: './ecommerce-api/Dockerfile'
    ports:
      - "8081:80"
  client:
    build:
      context: ../
      dockerfile: './ecommerce-admin-web/Dockerfile'
    ports:
      - "8082:4200"
      - "49153:49153"
    volumes:
      - "../ecommerce-admin-web/dist/ecommerce-admin-web:/usr/share/nginx/html:ro"